### PR TITLE
work on windows

### PR DESCRIPTION
**Pull request by mattn**
1. disable colors on windows in defaults (related on #39)
2. escape with double quote on windows

### CODE REVIEW

**Comment by weakish** [comment]
@mattn 

I guess maybe the pull request was closed because the color issue is better to be fixed in the upstream python module.

BTW, I cherry-picked the double quotes escaping commit.

**Comment by mattn** [comment]
I don't remember what I want to fix at least because this PR is made in 2012. too old.

**Comment by weakish** [comment]
@mattn 

It seems your PR fix two issues:

1. color output on windows cmd prompt (this has been fixed in the upstream python module, a.k.a. clint)
2. double quotes escaping path (Windows cmd does not understand single quoted)

**Comment by mattn** [comment]
Okay, I understand. Thank you.

**Pull request closed without merging**
