### PR TITLE
remove old reference to six

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by weakish** [comment]
Thanks for contributing to legit.

Sorry I am not familiar with pipenv.
Can you add more information about why the reference to `six` is considered "old"?

My attempt to figure out which library depends on `six`:

I run `pipenv graph` (Python 3.11.6, macOS Ventura),
and it seems that `six` is still used by one of the indirect dependency:

```
; pipenv graph
# ... (unrelated graph omitted)
pytest-cov==2.7.1
# ...
└── pytest [required: >=3.6, installed: 5.1.2]
# ...
    ├── packaging [required: Any, installed: 19.2]
    │   ├── pyparsing [required: >=2.0.2, installed: 2.4.2]
    │   └── six [required: Any, installed: 1.11.0]
```

In other words, according to `pipenv graph`, pytest-cov depends on pytest, pytest depends on packaging, and packaging depends on six.

**Comment by frostming** [comment]
Run a real `pipenv update` instead of only removing one entry.

**Comment by a-detiste** [comment]
Thanks.  I ll send a PR against packaging first.

I never used pipenv, I m used to package everything and the rest as Debian
packages.

**Comment by weakish** [comment]
> I ll send a PR against packaging first.

@a-detiste Recent versions of packaging do not depend on six any more. (pypa/packaging#331)

I think you may update the version requirement for pytest and pytest-cov in Pipfile,
then run `pipenv update` to update the lock file and check if all tests still passed.

(I'll leave this PR as closed for now but feel free to push new changes to your branch.
And when it is ready, we can reopen and merge it. Or you can create a new PR if you find that is more convenient for you.)

**Pull request closed without merging**
